# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='products_collect', to='product.ProductCollectionPoint', verbose_name='Local de coleta/colheita'),
        ),
    ]
