# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171115_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provenance',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('plantio', 'Plantio'), ('saf', 'SAF')], max_length=255, null=True, verbose_name='Procedência'),
        ),
    ]
