# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171122_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHarvestPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_period', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255, verbose_name='Período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período da safra',
                'verbose_name_plural': 'Períodos de safra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='benefit_sharing_value',
            field=models.CharField(blank=True, choices=[('Patrimônio genético', 'Patrimônio genético'), ('CTA identificável', 'CTA identificável'), ('CTA não identificável', 'CTA não identificável')], max_length=255, null=True, verbose_name='Regra de repartição de benefício'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='harvest_period',
        ),
        migrations.AlterField(
            model_name='product',
            name='provenance',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Plantio', 'Plantio'), ('SAF', 'SAF')], max_length=255, null=True, verbose_name='Procedência'),
        ),
        migrations.AlterField(
            model_name='productcollectionpoint',
            name='location_type',
            field=models.CharField(choices=[('Área própria', 'Área própria'), ('Área compartilhada', 'Área compartilhada'), ('Área cedida', 'Área cedida'), ('Praia', 'Praia'), ('Rio', 'Rio')], max_length=255, verbose_name='Local da coleta/colheita'),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_period',
            field=models.ManyToManyField(blank=True, help_text='Informações sobre o período da safra', null=True, to='product.ProductHarvestPeriod', verbose_name='Período da safra'),
        ),
    ]
