# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='leadership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.CommunityLeadership', verbose_name='Liderança'),
        ),
    ]
