# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20171115_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCraftwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artesanato',
                'verbose_name_plural': 'Artesenatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityCraftworkPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da imagem')),
                ('image', models.ImageField(upload_to='community/craftwork/pictures/%y/%m', verbose_name='Imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('craftwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.CommunityCraftwork', verbose_name='Comunidade')),
            ],
            options={
                'verbose_name': 'Imagem de artesanato',
                'verbose_name_plural': 'Imagens de artesanato',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='community',
            name='craftwork',
        ),
        migrations.AlterField(
            model_name='community',
            name='energy_type',
            field=models.CharField(blank=True, choices=[('monofasica', 'Monofásica'), ('bifasica', 'Bifásica')], max_length=255, null=True, verbose_name='Tipo de energia elétrica'),
        ),
        migrations.AlterField(
            model_name='communitypicture',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.Community', verbose_name='Comunidade'),
        ),
        migrations.AddField(
            model_name='communitycraftwork',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craftworks', to='community.Community', verbose_name='Comunidade'),
        ),
    ]
