# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_auto_20171024_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('target_area', models.TextField(blank=True, verbose_name='Área de atuação')),
                ('theme_description', models.TextField(blank=True, verbose_name='Tema')),
                ('goals', models.TextField(blank=True, verbose_name='Objetivos')),
                ('specific_goals', models.TextField(blank=True, null=True, verbose_name='Objetivos específicos')),
                ('activities', models.TextField(blank=True, verbose_name='Atividades a serem desenvolvidas')),
                ('results', models.TextField(blank=True, verbose_name='Resultados esperados')),
                ('schedule', models.FileField(blank=True, help_text='Arquivo PDF com o cronograma do projeto', upload_to='project/schedules/%y/%m', verbose_name='Cronograma')),
                ('target_audience', models.TextField(blank=True, verbose_name='Público alvo')),
                ('budget', models.FileField(blank=True, help_text='Aquivo PDF com o orçamento do projeto', upload_to='project/budgets/%y/%m', verbose_name='Orçamento')),
                ('project_totals', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor total do projeto')),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, help_text='Percentagem do valor do projeto que será                                 destinado ao administrativo', max_digits=5, null=True, verbose_name='Valor do administrativo')),
                ('community_tour', models.BooleanField(help_text='Assinala caso seja projeto de visita                                                     comunitária', verbose_name='Visita comunitária')),
                ('future_vision', models.TextField(blank=True, help_text='Breve resumo de qual seria a visão de futuro                                                  da comunidade com a execução do projeto.', verbose_name='Visão de futuro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria de projeto',
                'verbose_name_plural': 'Categorias de projeto',
            },
        ),
        migrations.CreateModel(
            name='ProjectPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome da imagem')),
                ('image', models.ImageField(blank=True, upload_to='project/pictures/%y/%m', verbose_name='Imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Imagem do projeto',
                'verbose_name_plural': 'Imagens do projeto',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='project_categories', to='project.ProjectCategory', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_projects', to='community.Community', verbose_name='Comunidade'),
        ),
    ]
