# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activities',
            field=models.TextField(blank=True, null=True, verbose_name='Atividades a serem desenvolvidas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='future_vision',
            field=models.TextField(blank=True, help_text='Breve resumo de qual seria a visão de futuro                                                  da comunidade com a execução do projeto.', null=True, verbose_name='Visão de futuro'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, null=True, verbose_name='Resultados esperados'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_area',
            field=models.TextField(blank=True, null=True, verbose_name='Área de atuação'),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme_description',
            field=models.TextField(blank=True, null=True, verbose_name='Tema'),
        ),
    ]
