# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20171115_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.Project', verbose_name='Projeto    '),
        ),
    ]
