# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('company_reg', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('sector', models.CharField(max_length=255, verbose_name='Setor')),
                ('type', models.CharField(max_length=255, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='address.Address', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
